[logger]
level = "info"

[runner]
fastReruns = false
magicEnabled = false


[server]
enableCORS = false
enableXsrfProtection = false
folderWatchBlacklist = ['logs', '.git', 'settings', 'workdir', 'output']
headless = true
address = "0.0.0.0"

[browser]
gatherUsageStats = false
